# Generated by Django 5.1.6 on 2025-03-10 15:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=500)),
                ('image', models.ImageField(upload_to='abhay/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('rm', 'random'), ('sf', 'self'), ('gf', 'girlfrend')], max_length=2)),
            ],
        ),
    ]
