# Generated by Django 5.1.7 on 2025-03-12 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abhay', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='image',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='type',
        ),
    ]
