# Generated by Django 5.1.7 on 2025-03-12 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abhay', '0003_comment_email_comment_name_comment_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='text',
        ),
        migrations.AddField(
            model_name='comment',
            name='feedback',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='comment',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
