# Generated by Django 5.1.7 on 2025-03-14 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abhay', '0004_remove_comment_text_comment_feedback_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('whathapp', models.CharField(max_length=10)),
            ],
        ),
    ]
