# Generated by Django 5.1.7 on 2025-03-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abhay', '0008_alter_contact_whathapp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='whathapp',
        ),
        migrations.AddField(
            model_name='contact',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
