# Generated by Django 5.1.7 on 2025-03-17 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abhay', '0010_alter_contact_phone_alter_contact_whatsapp_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
